#!/bin/sh
EXE=/usr/bin/md5sum
FILE=/var/run/config.md5

cd $(mktemp -d) || return 1
ls /etc/config | while read conf; do uci show $conf > $conf; done
[ -f $FILE ] && {
	$EXE -c $FILE | awk -F: '/FAILED$/{print $1}' | while read conf; do
		ubus call service event \
			"{'type':'config.change','data':{'package':'$conf'}}"
	done
} &>/dev/null
$EXE * > $FILE
cd $OLDPWD && rm -rf $OLDPWD
